// TYPES
export const GET_ALL_CONVENIENCES = 'GET_ALL_CONVENIENCES';
export const SET_CONVENIENCES_LOADING = 'SET_CONVENIENCES_LOADING';
export const SET_CONVENIENCES_ERROR = 'SET_CONVENIENCES_ERROR';
export const ADD_CONVENIENCES = 'ADD_CONVENIENCES';
export const FIND_CONVENIENCES = 'FIND_CONVENIENCES';
export const UPDATE_CONVENIENCES = 'UPDATE_CONVENIENCES';
export const DELETE_CONVENIENCES = 'DELETE_CONVENIENCES';
